# Generated by Django 5.0.7 on 2025-01-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finance', '0009_alter_student_payment_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelbill',
            name='academic_fees',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='levelbill',
            name='exams_fees',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='levelbill',
            name='student_fees',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
